include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.cscs.yml'

stages:
  - build
  - test

##
## BUILDS
##
.build_common:
  extends: .dind
  stage: build
  only: ['master', 'staging', 'trying']
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --network=host --cache-from $BUILD_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 -t $BUILD_IMAGE -f $BUILD_DOCKERFILE .
    - docker push $BUILD_IMAGE
    - docker build -t $DEPLOY_IMAGE --network=host --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg BUILD_ENV=$BUILD_IMAGE -f $DEPLOY_DOCKERFILE .
    - docker push $DEPLOY_IMAGE

# Builds a Docker image for the current commit, cpu / gpu
build sanitizer cpu:
  extends: .build_common
  variables:
    BUILD_DOCKERFILE: docker/asan/build-env.Dockerfile
    BUILD_IMAGE: $CI_REGISTRY_IMAGE/build-env-asan:latest
    DEPLOY_DOCKERFILE: docker/asan/deploy.Dockerfile
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE/deploy-cpu-asan:$CI_COMMIT_SHA

build cpu:
  extends: .build_common
  variables:
    BUILD_DOCKERFILE: docker/cpu-release/build-env.Dockerfile
    BUILD_IMAGE: $CI_REGISTRY_IMAGE/build-env-cpu:latest
    DEPLOY_DOCKERFILE: docker/cpu-release/deploy.Dockerfile
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE/deploy-cpu:$CI_COMMIT_SHA


build gpu:
  extends: .build_common
  variables:
    BUILD_DOCKERFILE: docker/gpu/build-env.Dockerfile
    BUILD_IMAGE: $CI_REGISTRY_IMAGE/build-env-gpu:latest
    DEPLOY_DOCKERFILE: docker/gpu/deploy.Dockerfile
    DEPLOY_IMAGE: $CI_REGISTRY_IMAGE/deploy-gpu:$CI_COMMIT_SHA

sanitize:
  stage: test
  only: ['master', 'staging', 'trying']
  trigger:
    strategy: depend
    include: /ci/sanitize.yml

cpu test:
  stage: test
  only: ['master', 'staging', 'trying']
  trigger:
    strategy: depend
    include: /ci/cpu.yml

gpu test:
  stage: test
  only: ['master', 'staging', 'trying']
  trigger:
    strategy: depend
    include: /ci/gpu.yml
